S2S:
  n_vocab: 21
  d_struct: 120
  COTRM:
    d_model: 128
    nhead: 8
    nlayer: 6
    d_ffn: 1024
    dropout: 0.1
    TRM:
      d_model: 128
      nhead: 8
      nlayer: 6
      d_ffn: 1024
      d_input: 120
      dropout: 0.1

SeqRecover:
  mask_ratio: 1
  d_model: 128
  nhead: 8
  nlayer: 6
  d_ffn: 1024
  d_input: 120
  dropout: 0.1

StructRecover:
  mask_ratio: 1
  d_model: 128
  nhead: 8
  nlayer: 1
  d_ffn: 1024
  d_input: 120
  dropout: 0.1

TRAIN:
  batch_size: 128
  lr: 0.001
  epochs: 50
  mask_ratio: 0.5
  Seq2Struct:
    mask_ratio: 0.5
  Struct2Seq:
    mask_ratio: 0.5

CrossAttn:
  n_vocab: 21
  d_struct: 120
  d_model: 128
  n_head: 8
  nlayer: 1
  d_ffn: 1024
  dropout: 0.1


